title: FIRE関連のページ
remote_theme: just-the-docs/just-the-docs
permalink: /:basename.html

# 検索機能を有効にする設定
search_enabled: true
search:
  tokenizer_separator: /[\s\-]+/  # 検索ワードを区切るルール（日本語検索を安定させるため）